Repository poly-team/poly_events_mobile, pull requests merged in 2021-07, with the labels that each got.

#16 [Feature/PE1-30] Rename design files
  designs/home_page_no_events.png
  designs/home_page_no_events_image.png
  designs/home_page_with_events.png
Labels: automerge

#15 [Feature/PE1-28] Add design files
  designs/forgot_password_page.png
  designs/login_page.png
  designs/poly_events_logo_version_1.png
  designs/poly_events_logo_version_2.png
  designs/sign_up_page.png
  designs/welcome_page.png
Labels: automerge, help wanted

#19 [Feature/PE1-29] Change README.md
  README.md
Labels: automerge, good first issue, help wanted
