Repository poly-team/poly_events_mobile, pull requests merged in 2021-06, with the labels that each got.

#1 [Feature/PE1-3] Update names and descriptions
  .github/workflows/auto-merge.yml
  .github/workflows/flutter-analyze.yml
  .github/workflows/flutter-build.yml
  .github/workflows/ticket-check.yml
Labels: automerge, good first issue, help wanted

#4 [Feature/PE1-20] Add contributor names
  README.md
Labels: automerge, good first issue, help wanted

#7 [Feature/PE1-21] Introduction and organization of image assets
  assets/images/PEcircle1.png
  assets/images/PEcircle2.png
  assets/images/PElogin2.png
  assets/images/PEloginImage.png
  assets/images/PErectangle1.png
  assets/images/PEsignup.png
  assets/images/PEwelcomeImage.png
Labels: automerge, help wanted, urgent

#6 [Feature/PE1-15] Added the icon to the app
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/flutter_icon.png
  android/app/src/main/res/mipmap-mdpi/flutter_icon.png
  android/app/src/main/res/mipmap-xhdpi/flutter_icon.png
  android/app/src/main/res/mipmap-xxhdpi/flutter_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/flutter_icon.png
  assets/icon/PElogo1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.lock
  pubspec.yaml
Labels: automerge

#12 [Feature/PE1-26] Add basic home page design files
  designs/PEhomepage1.png
  designs/PEhomepage2.png
  designs/PEhomepageImage.png
Labels: automerge

#13 [Feature/PE1-27] Update README.md
  README.md
Labels: automerge
